### ISSUE TITLE
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

### ISSUE THREAD

**Issue by purusha** [dunky11/react-saas-template#113] opened 2020-02-18 08:03 UTC
I followed the instructions to start the project, but I get an error on startup:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.13.4
3 info using node@v12.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-saas-template@1.0.0~prestart: react-saas-template@1.0.0
6 info lifecycle react-saas-template@1.0.0~start: react-saas-template@1.0.0
7 verbose lifecycle react-saas-template@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle react-saas-template@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/osboxes/dev/github/react-saas-template/node_modules/.bin:/home/osboxes/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle react-saas-template@1.0.0~start: CWD: /home/osboxes/dev/github/react-saas-template
10 silly lifecycle react-saas-template@1.0.0~start: Args: [ '-c', 'node scripts/start.js' ]
11 silly lifecycle react-saas-template@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle react-saas-template@1.0.0~start: Failed to exec start script
13 verbose stack Error: react-saas-template@1.0.0 start: `node scripts/start.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid react-saas-template@1.0.0
15 verbose cwd /home/osboxes/dev/github/react-saas-template
16 verbose Linux 4.18.0-25-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.16.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error react-saas-template@1.0.0 start: `node scripts/start.js`
22 error Exit status 1
23 error Failed at the react-saas-template@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dunky11** [comment] 2020-02-18 11:34
Ye, i think it had something to do with react-dev-utils. For some reason it passed my tests. I updated the repository.

Can you try:
```
git pull
npm prune
npm install
npm start
```

**Comment by purusha** [comment] 2020-02-20 07:17
$> npm start
> react-saas-template@1.0.0 start /home/osboxes/dev/github/react-saas-template
> react-scripts start

internal/modules/cjs/loader.js:984
  throw err;
  ^

Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Require stack:
- /home/osboxes/dev/github/react-saas-template/node_modules/html-webpack-plugin/lib/compiler.js
- /home/osboxes/dev/github/react-saas-template/node_modules/html-webpack-plugin/index.js
- /home/osboxes/dev/github/react-saas-template/node_modules/react-scripts/config/webpack.config.js
- /home/osboxes/dev/github/react-saas-template/node_modules/react-scripts/scripts/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/osboxes/dev/github/react-saas-template/node_modules/html-webpack-plugin/lib/compiler.js:14:28)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/osboxes/dev/github/react-saas-template/node_modules/html-webpack-plugin/lib/compiler.js',
    '/home/osboxes/dev/github/react-saas-template/node_modules/html-webpack-plugin/index.js',
    '/home/osboxes/dev/github/react-saas-template/node_modules/react-scripts/config/webpack.config.js',
    '/home/osboxes/dev/github/react-saas-template/node_modules/react-scripts/scripts/start.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-saas-template@1.0.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-saas-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osboxes/.npm/_logs/2020-02-19T07_52_29_152Z-debug.log

$> cat 2020-02-19T07_52_29_152Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.13.4
3 info using node@v12.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-saas-template@1.0.0~prestart: react-saas-template@1.0.0
6 info lifecycle react-saas-template@1.0.0~start: react-saas-template@1.0.0
7 verbose lifecycle react-saas-template@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle react-saas-template@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/osboxes/dev/github/react-saas-template/node_modules/.bin:/home/osboxes/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle react-saas-template@1.0.0~start: CWD: /home/osboxes/dev/github/react-saas-template
10 silly lifecycle react-saas-template@1.0.0~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle react-saas-template@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle react-saas-template@1.0.0~start: Failed to exec start script
13 verbose stack Error: react-saas-template@1.0.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid react-saas-template@1.0.0
15 verbose cwd /home/osboxes/dev/github/react-saas-template
16 verbose Linux 4.18.0-25-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.16.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error react-saas-template@1.0.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the react-saas-template@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dunky11** [comment] 2020-02-20 14:12
I cant reproduce this error, neither on Windows 10 nor on Ubuntu 19.04.

However I found a thread on the webpack forum about it.

https://github.com/webpack/webpack/issues/2131

If you have webpack installed globally, try removing it:

`npm remove webpack -g`

**Comment by dunky11** [comment] 2020-04-12 20:02
I do not think it has something to do with the repo and there is no reaction, im gonna close this.

**Closed by dunky11** 2020-04-12 20:02 UTC
Labels: bug
