### ISSUE TITLE
Chrome v88 JSS issue

### ISSUE THREAD

**Issue by bonomite** [dunky11/react-saas-template#296] opened 2021-01-20 14:47 UTC
I recently updated my Chrome browser to v88 and the site crashed. After investigation, I narrowed it down to this line int he PriceCard.js

borderRadius: theme.shape.borderRadius * 2

Once I removed the "* 2" the site worked again.

**Comment by dunky11** [comment] 2021-01-21 08:28
Thank! Im gonna have a look at it!

**Comment by bonomite** [comment] 2021-01-21 17:47
You're welcome! This started template is very good. Thank you.

**Comment by dunky11** [comment] 2021-01-22 19:03
Thanks :) 

I couldn't reproduce this on Chrome 88 on Ubuntu 20.04.

The bug seems weird, If someone else is reporting this problem I am gonna investigate this further.

**Comment by bonomite** [comment] 2021-01-23 16:57
Odd. I'm on windows.  Thanks again.

**Comment by dunky11** [comment] 2021-03-08 10:24
I'm gonna close this since nobody else faced this issue yet.

**Closed by dunky11** 2021-03-08 10:24 UTC
