### ISSUE TITLE
Browser Back button required twice in the logged in section

### ISSUE THREAD

**Issue by madomingo** [dunky11/react-saas-template#430] opened 2021-05-02 08:11 UTC
Once logged in, navigate through the NavBar icons (Dashboard, Posts, Subscriptions). If you press the Back button in the browser to navigate to the previous, it shows the same section and it is required to press the Back button a second time to navigate to the previous section.
Can be reproduced in the demo site.

**Comment by dunky11** [comment] 2021-05-03 14:42
I can reproduce this issue, thanks :) Im gonna investigate this further ...

**Comment by dunky11** [comment] 2021-05-03 15:41
should be fixed in https://github.com/dunky11/react-saas-template/commit/17f8717331bdd95a43b29aeec6ab4e2e298ee6d6

 The problem was that the behaviour of react-router changed from v3 to v4. If a link is now clicked n times, you also have to click the back button n times to go back to the page. Lets hope my fix doesn't introduce new bugs :))

**Comment by madomingo** [comment] 2021-05-05 11:09
Thank you @dunky11  , I have been testing the fix and works ok, could not find any bug.

**Closed** 2021-05-05 20:08 UTC
