### ISSUE TITLE
Opening modals causes weird look

### ISSUE THREAD

**Issue by Danon** [dunky11/react-saas-template#192] opened 2020-06-21 10:19 UTC
As a logged user, when I open Credit Card dialog or open messages popup, then the height of the page changes, the scroll bar disappears, and leaves the top navbar "cut-out"

![image](https://user-images.githubusercontent.com/13367735/85222173-67cc8600-b3b9-11ea-91d2-bf6eca8f0b4f.png)

**Comment by dunky11** [comment] 2020-06-22 03:57
Material-UI does that to prevent the screen from shaking when a modal is opened and the scrollbar disappears due to the new height. I tried to fix that but I think it can't be fixed without shaking the screen.
It shouldn't do that when opening the messages though and I can't reproduce it. Do you have something else opened in the screenshot which I can't see? Otherwise which browser do you use?

**Comment by dunky11** [comment] 2020-06-22 04:33
Adding the disableScrollLock prop fixed the issue. Fixed in https://github.com/dunky11/react-saas-template/pull/193.

**Closed** 2020-06-26 06:07 UTC
